[package]
name = "fields_macros"
version = "0.3.0"
edition = "2021"
authors = ["Zerthox"]

[lib]
proc-macro = true

[dependencies]
attribute-derive = "0.10.3"
heck = "0.5.0"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.71", features = ["full"] }
